relativeURLs = true
title = "Vaishnavi Surendra"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Development Economist"
    logo = "profile-picture.jpg" 
    
